plugins {
    id 'com.android.application'
}

android {
    namespace 'com.antenna.speedlimiter'
    compileSdk 34
    ndkVersion '29.0.14206865'

    defaultConfig {
        applicationId 'com.antenna.speedlimiter'
        minSdk 24
        targetSdk 34
        versionCode 4
        versionName '1.4'

        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a'
        }

        externalNativeBuild {
            ndkBuild {
                arguments 'APP_CFLAGS+=-DPKGNAME=com/antenna/speedlimiter -DCLSNAME=SpeedVpnService -ffile-prefix-map=' + rootDir + '=.'
                arguments 'APP_LDFLAGS+=-Wl,--build-id=none'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    externalNativeBuild {
        ndkBuild {
            path 'src/main/jni/Android.mk'
        }
    }
}
